services:
  local-mysql:
    image: mysql
    container_name: dohyun-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    platform: linux/arm64

  local-redis:
    image: redis
    container_name: dohyun-redis
    ports:
      - "6379:6379"
    platform: linux/arm64
